server:
  port: 8080
 
eureka:
  instance:    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1  client:    serviceUrl:
       defaultZone: http://localhost:8761/eureka    healthcheck:      enabled: true

spring:  application:    name: shop-service
